### PR TITLE
support mocha multi reporter

### PR DESCRIPTION
**Pull request by luigisamurai**
Hi, I want to merge it to support mocha multi [issue](https://github.com/yandex/mocha-parallel-tests/issues/136).  I don`t know the process to contribute with this project but I going to trying.

I Added support to  [mocha multi reporter](https://github.com/glenjamin/mocha-multi), it added the path of the mocha multi reporter and it transformed the parameter reporterOptions to work with mocha multi.

to use it from a project that has installed **mocha-parallel-tests** you should:

1. install mocha multi 
      ``` npm install mocha-multi --save-dev ```
1. specify the parameter --reporter or -R and --reporter-options
      ``` mocha-parallel-tests -- --reporter mocha-multi --reporter-options dot=-,xunit=file.xml,doc=docs.html ```

I kept the same format specified in https://github.com/glenjamin/mocha-multi#with---reporter-options

### CODE REVIEW

**Comment by 1999** [comment]
Hey @luigisamurai thank you for PR, PRs are always a great way to start an issue. Usually I ask contributors to add a test so we can cover the new functionality with it. It's also a bit unclear to me why current mocha-parallel-tests code is not working for you. As far as I know you can just run `mocha-parallel-tests -R mocha-multi --reporter-options dot=-,xunit=file.xml,doc=docs.html` and it should wok fine for you. Or maybe it's broken somehow?

**Comment by luigisamurai** [comment]
Hi, I agree to add the unit test, I going doing it.
I need this pull request because Mocha Multi expects that the reporter-options to be  an object  and with mocha-parallel-test arrives a string instead if I run with mocha, it parameter arrives how object

**Comment by 1999** [comment]
Hm... That's interesting. If it's possible (mocha function which does reporterOptions parsing is exported) please import it and re-use it. Otherwise I'm happy to review your PR and merge it.

**Comment by luigisamurai** [comment]
Thank Dmitrii Sorin, you are right. **mocha parallel tests** works with **mocha multi**.  I was not passing the shell variable **multi** for this reason, I close it

thanks you

**Comment by 1999** [comment]
No worries, feel free to ping me if you have any other issues.
Just in case: I'm working on v2 right now and some of the API can break (possibly own options): https://github.com/yandex/mocha-parallel-tests/issues/126

**Pull request closed without merging**
