### PR TITLE
skip binary modules during cache reset

### PR DESCRIPTION
**Pull request by kolontsov**
https://github.com/yandex/mocha-parallel-tests/issues/100

### CODE REVIEW

**Comment by 1999** [comment]
Good job! Would you mind writing a test for this case?

**Comment by kolontsov** [comment]
Thanks! No problem, but I have doubts about implementation: good test should use binary module, so we need to find it somewhere. Add something "small & binary" to `devDependancies`? Or compile own minimal 3-line module from source (it will require installing node-gyp npm).. 

Any suggestion?

**Comment by 1999** [comment]
> Add something "small & binary" to devDependancies

Compiling our own module for this case seems to be a bit more fair, but unfortunately I'm not familiar with it. If it doesn't take a lot of time for you, it would be great. If it does, just add a small/existing binary module to devDependencies.

**Comment by kolontsov** [comment]
Sure, I'll implement it (sorry for pause)

**Comment by 1999** [comment]
Yes, AWS can interfere in tests results. Let's just wait for tomorrow.

**Comment by kolontsov** [comment]
Test passes on all node.js versions except 'stable' 7.7.0, which was released today (2017-03-01).
They completely broke compiling addons: https://github.com/nodejs/node/issues/11628. Waiting for a fix.

**Comment by kolontsov** [comment]
Node.js [released](https://nodejs.org/en/blog/release/v7.7.1/) fixed stable version, could you please restart Travis build?

**Comment by 1999** [comment]
Nice one! Will release a new version today/tomorrow.

**Pull request merged**
